### ISSUE TITLE
Build book throws error, preview book works fine

### ISSUE THREAD

**Issue by dcossyleon** [dcossyleon/test_book#1]
Hey @apreshill, starting a brand new bookdown with `bookdown:::bookdown_skeleton(getwd())`. When I go to "Build Book", though, I get an error:

![image](https://user-images.githubusercontent.com/29008894/62590713-447d1300-b89b-11e9-831d-c427bea15556.png)

But running *Addins* > *Preview Book*, there's no issue.  Any idea what might be going wrong?

The default `_output.yml` looks like this: 
```_output.yml

bookdown::gitbook:
  includes:
    in_header: header.html
  css: style.css
  config:
    toc:
      before: |
        <li><a href="./">A Minimal Book Example</a></li>
      after: |
        <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
    download: ["pdf", "epub"]
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: yes
bookdown::epub_book: default


```

**Comment by apreshill** [comment]
Ah build is building all output formats (including pdf and ebook), preview just “builds” gitbook html output format

**Comment by dcossyleon** [comment]
ok, that would explain it. 

But isn't it weird that the book skeleton defaults would result in an error for pdf book? For rstudio4edu, should we just advise to delete all the non-gitbook related output to avoid this error (since I'm assuming we're sticking with HTML always and forever), or should I dig in a little more into this error?

**Comment by apreshill** [comment]
Well this particular one is a latex install error, so I think it is "caveat emptor" whether you know you have a working latex distribution. So it isn't a problem with the book itself- it is a local user issue.

**Comment by apreshill** [comment]
To explain the difference, you may want to include a screenshot like this (the default is all formats in your `_output.yml`): 
<img width="599" alt="Screen Shot 2019-08-08 at 12 13 22 PM" src="https://user-images.githubusercontent.com/12160301/62730998-089a9880-b9d6-11e9-8591-ea6b380f796c.png">
